include(
    ":modules:features:main",
    ":modules:features:main:common",
    ":modules:features:feature1",
    ":modules:features:feature1:common",
    ":modules:features:feature2",
    ":modules:features:feature2:common",
    ":modules:features:splash",
    ":modules:features:splash:common",
    ":modules:features:welcome",
    ":modules:features:welcome:common",
    ":modules:features:profile",
    ":modules:features:profile:common",
)
